site_name: Saml2 Authentication
repo_url: https://github.com/dina-heidar/saml2-authentication
repo_name: dina-heidar/saml2-authentication
copyright: Copyright &copy; 2023 Dina Heidar

nav:
  - Home: "index.md"
  - Getting started:
    - Installation: getting-started.md  
    - Usage: 
      - MVC: usage/mvc-web.md
      - Razor Pages: usage/razor-pages.md
      - Blazor: usage/blazor-server.md
  - List of options: list-of-options.md

extra:  
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/@dina_heidar
      name: Dina Heidar on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/dina-heidar
      name: Dina Heidar on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/dina-heidar-072b28aa
      name: Dina Heidar on LinkedIn

theme:
  name: material
  logo: assets/icon_128x128.png
  favicon: images/favicon.png
  language: en
  font:
    text: Public Sans  
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.instant
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.top
    - toc.integrate
    - content.code.copy
    - navigation.expand
  palette:  
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
   - search
   - with-pdf:
      author: Dina Heidar
      cover_title: Saml2 Authentication
      cover_subtitle: Technical Documentation   
      cover_logo: ./assets/icon_500x500.png
      #back_cover: true
      toc_level: 2      
      two_columns_level: 0
      #render_js: true
      #headless_chrome_path: google-chrome      
      output_path: document.pdf     