site_name: Saml2Core
repo_url: https://github.com/squidfunk/mkdocs-material
repo_name: squidfunk/mkdocs-material
copyright: Copyright &copy; 2023 Dina Heidar

nav:
  - Overview: "index.md"

extra:  
  social:
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@squidfunk
      name: squidfunk on Fosstodon

theme:
  name: material
  language: en
  font:
    text: Public Sans
  features:
    - navigation.path
    - navigation.footer
    - content.code.copy
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
   - search
   - with-pdf:
      #cover_title:
      cover_subtitle: Technical documentation that just works      
      #back_cover: true
      toc_level: 2      
      two_columns_level: 3
      #render_js: true
      #headless_chrome_path: google-chrome      
      output_path: document.pdf     